### PR TITLE
bump mocha to 9.x and ensure lockfiles aren't created

### PR DESCRIPTION
**Pull request by jgravois**
i'm working on tracking down an error in prosemirror-collab and in the interim i noticed that a few more dependencies are needed to ensure a clean `npm i && npm test`.

* add `prosemirror-schema-basic`
* add `prosemirror-schema-list`
* bump mocha to 9.x to resolve a possible security vulnerability
* ensure that a package-lock.json file isn't created on `npm install` since you don't check them into version control.

happy to walk any of the individual items above back if they aren't desired. thanks for all your work on this project! 🥇

### CODE REVIEW

**Comment by marijnh** [comment]
How does this package use schema-basic/schema-list?

**Comment by jgravois** [comment]
apparently via `prosemirror-test-builder`.

https://github.com/ProseMirror/prosemirror-test-builder/blob/6b191acb3d82d0947f18ea0a67acc04d33bd996a/package.json#L19-L23

```bash
mac~/code/prosemirror-collab[deps L|✚1] % npm --version
6.14.11

mac~/code/prosemirror-collab[deps L|✚1] % npm test

> prosemirror-collab@1.2.2 test /Users/john/code/prosemirror-collab
> mocha test/test-*.js


Error: Cannot find module 'prosemirror-schema-list'
Require stack:
- /Users/john/code/prosemirror-collab/node_modules/prosemirror-test-builder/dist/index.js
```

**Comment by marijnh** [comment]
> apparently via prosemirror-test-builder.

Which depends on these packages, so it doesn't seem necessary to make this one also depend on them.

**Comment by jgravois** [comment]
i could be missing something, but prior to npm@7, peerDependencies for a package are _not_ installed by default.

https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependencies

**Comment by marijnh** [comment]
Oh, indeed, they are peer dependencies, weirdly—since none of the other packages work this way. More worryingly, that was the last patch to the test-builder repository, made last April, and I don't have any recollection of why I made it. I'm going to revert it, for the sake of consistency.

**Comment by jgravois** [comment]
i confirmed locally that 1.0.5 does the trick!

i've pushed up another commit that reverts those additions just in case there's anything else in this PR that looks useful.

**Comment by marijnh** [comment]
I've applied your other changes for all packages (see d90d060cdf92e13012911bc3d2b2a71d54dab5fd and bfa5940a9b4621df5ff40092598c956ba0c30a7d in this repository).

**Pull request closed without merging**
